baseURL = 'https://bouligny.dev/'
languageCode = 'en-us'
title = "Jon's Devlog"
theme = 'ananke'

[markup.goldmark.renderer]
  unsafe = true

[params]
  mainSections = ['fleet-platform']
  images = ['images/og-default.png']
  favicon = 'favicon.ico'

[params.ananke.social.follow]
  networks = ["github", "linkedin", "email"]

[params.ananke.social.github]
  username = "JonathanBouligny"

[params.ananke.social.linkedin]
  username = "jonathan-j-bouligny"
  profilelink = "https://www.linkedin.com/in/jonathan-j-bouligny"

[params.ananke.social.email]
  profilelink = "mailto:jonathanbouligny@gmail.com"

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 10
  [[menus.main]]
    name = 'Fleet Platform'
    pageRef = '/fleet-platform'
    weight = 20
